version: "3.7"

services:
  test:
    build: .
    image: nested_select
    command: rake test
    volumes:
      - './lib:/app/lib'
      - './test:/app/test'
      - './Gemfile:/app/Gemfile'
      - './Gemfile.lock:/app/Gemfile.lock'

  appraisal:
    build:
      context: .
      dockerfile: Dockerfile_apprsl
    image: nested_select_appraisal
    command: /bin/bash -c 'service postgresql start && appraisal rake test'
    volumes:
      - '.:/app'
