require_relative  "../models/application_record"
require_relative  "../models/user"
require_relative  "../models/avatar"
require_relative  "../models/item"
require_relative  "../models/image"
require_relative  "../models/user_profile"
require_relative "migrations"
